language: python
sudo: required
python:
 - "3.4.3"

install:
- cd Python
- pip install -r requirements.txt 

script:
- coverage run --source=scriptAnime.py test_totales.py

after_success:  
  - coveralls
