language: python
sudo: required
python:
 - "3.4.3"

install:
- cd Python
- pip install -r requirements.txt 

script:
- nosetests --with-coverage --omit=/usr/lib/python3.4/webbrowser.py

after_success:  
  - coveralls
